### ISSUE TITLE
Why the old urllib3 pinned version?

### ISSUE THREAD

**Issue by darkvertex** [tink-crypto/tink-py#13]
**Describe the bug:**

It would be cool to know why the urllib3 version that is pinned as a requirement is such an old one?

In the real release, as per:
https://github.com/tink-crypto/tink-py/blob/5934f47df29666ccadaa5ff4cc2ba626f82bcdf5/requirements.txt#L256
you pin it at `urllib3==1.26.16`
yet deeper in the repo you have a `release_requirements.txt` file with a newer version:
https://github.com/tink-crypto/tink-py/blob/5934f47df29666ccadaa5ff4cc2ba626f82bcdf5/kokoro/release_requirements.txt#L271
at `urllib3==2.0.2`, almost the newest of 2.0.4.

I had upgraded from tink 1.7.0 and it downgraded urllib3 in my project in the process.

**What version of Tink are you using?**

1.8.0

**Comment by morambro** [comment]
> It would be cool to know why the urllib3 version that is pinned as a requirement is such an old one?

This is a transitive dependency. `google-auth` [requires `urllib3<2.0`](https://github.com/googleapis/google-auth-library-python/blob/2885211827ae9280cd355ef6c796882a597b1abb/setup.py#L30), so `pip-compile` uses it when generating `requirements.txt`. `google-auth` is a new dependency needed by the Python native Google Cloud KMS extension.

Note that when you install `tink` via `pip install` transitive dependencies will be resolved by `pip` and not pinned to `requirements.txt`; the constraints Tink declares are in [`requirements.in`](https://github.com/tink-crypto/tink-py/blob/5934f47df29666ccadaa5ff4cc2ba626f82bcdf5/setup.py#L224).

> yet deeper in the repo you have a `release_requirements.txt` file with a newer version:

These are dependencies required by our [release tooling](https://github.com/tink-crypto/tink-py/blob/5934f47df29666ccadaa5ff4cc2ba626f82bcdf5/kokoro/release_on_pypi.sh#L131) so it doesn't have the same constraints.

**Comment by darkvertex** [comment]
Ahhh, I had not seen the `requirements.in`. Thank you for the explainer.
