### ISSUE TITLE
Support 3.12 and build a wheel

### ISSUE THREAD

**Issue by Redoubts** [tink-crypto/tink-py#30]
Can a pypi wheel be made available for 3.12 for this project?

**Comment by morambro** [comment]
3.12 is now supported and a wheel will be created for the v1.10.0 release.

**Comment by Redoubts** [comment]
Great, thank you. When do you anticipate that release will be published?

**Comment by morambro** [comment]
I am working on it, hopefully by the end of the month

**Comment by morambro** [comment]
v1.10.0 is out https://pypi.org/project/tink/1.10.0/
