### ISSUE TITLE
Internal use of JsonKeysetWriter, which is deprecated

### ISSUE THREAD

**Issue by ahyatt-continua** [tink-crypto/tink-py#34]
At _json_proto_keyset_format.py:83 (in my 1.10 Python Tink, and also in your repository in HEAD), you use `JsonKeysetWriter`, which is deprecated.

I don't think a library should be printing out deprecation warnings about internal usage of deprecated functions, since users have no way of fixing it.

Also, it's a bit worrying: is the deprecation something I, as a user, need to be concerned about?

I think either fixing the use (using the replacement suggested in the `JsonKeysetWriter` class), or simply removing the warning would be a good fix for this issue.

**Comment by juergw** [comment]
I agree, I removed the warning.

**Comment by juergw** [comment]
Here: https://github.com/tink-crypto/tink-py/commit/71752eaf810e55d286114d437ca556d378d1a6d6
